---
title: "Untitled"
output: html_document
---

```{r}
library(conflicted)
library(ktplots)
data(kidneyimmune)
data(cpdb_output2)

library(ggraph)
library(dplyr)
conflict_prefer("filter", "dplyr")
library(readr)
```

```{r}
cpdb_res = read_tsv("/home/sturm/Downloads/differential_signature_patient_immune_infiltration_cpdb.tsv")

```
```{r}
edges = cpdb_res |>
  filter(fdr < 0.1, coef > 0) |>
  mutate( from=sprintf("%s_%s_ligand", cluster_1, source), to=sprintf("%s_%s_receptor", cluster_2, target)) |>
  select(from, to, name="...1", coef, pvalue, fdr, group)
```

```{r}
nodes_source = cpdb_res |> 
  select(cell_type=cluster_1, gene=source) |>
  mutate(type="ligand") |>
  mutate(name=sprintf("%s_%s_%s", cell_type, gene, type))
nodes_target = cpdb_res |> 
  select(cell_type=cluster_2, gene=target) |>
  mutate(type="receptor") |>
  mutate(name=sprintf("%s_%s_%s", cell_type, gene, type))
nodes = bind_rows(nodes_source, nodes_target) |>
  distinct() |>
  select(name, cell_type, gene, type) |>
  filter(name %in% edges$to | name %in% edges$from)

```


<!-- # ```{r} -->
<!-- # G = graph_from_data_frame(edges, directed=TRUE, vertices=nodes |> filter(name %in% edges$from | name %in% edges$to)) -->
<!-- #  -->
<!-- # ``` -->

```{r}
cell_types = unique(c(cpdb_res$cluster_1, cpdb_res$cluster_2))
cell_type_lr = unique(paste0(nodes$cell_type, "_", nodes$type))
# construct hierarchy
edges_ct_hierarchy = bind_rows(
  # root
  data.frame(from="root", to=nodes$cell_type),
  nodes |> mutate(to=paste0(cell_type, "_", type)) |> select(from=cell_type, to) |> distinct(),
  nodes |> mutate(from=paste0(cell_type, "_", type), to=name) |> select(from, to)
)
nodes_ct_hierarchy = data.frame(name=unique(c(edges_ct_hierarchy$to, edges_ct_hierarchy$from))) |> 
  left_join(nodes) |> group_by(cell_type) |>  group_modify(function(x, key) { 
    n = nrow(x)
    n1 = floor(n/2)
    n2 = n - 1 - n1
    x$cell_type_label = c(rep(NA, n1), key$cell_type, rep(NA, n2))
    x
  }) |> ungroup() |> select(name, cell_type, gene, type, cell_type_label)
G_ct =graph_from_data_frame(edges_ct_hierarchy, directed=TRUE, vertices=nodes_ct_hierarchy)
```
```{r}
zeileis_28 = c(
    "#023fa5",
    "#7d87b9",
    "#bec1d4",
    "#d6bcc0",
    "#bb7784",
    "#8e063b",
    "#4a6fe3",
    "#8595e1",
    "#b5bbe3",
    "#e6afb9",
    "#e07b91",
    "#d33f6a",
    "#11c638",
    "#8dd593",
    "#c6dec7",
    "#ead3c6",
    "#f0b98d",
    "#ef9708",
    "#0fcfc0",
    "#9cded6",
    "#d5eae7",
    "#f3e1eb",
    "#f6c4e1",
    "#f79cd4",
    # these last ones were added:
    '#7f7f7f',
    "#c7c7c7",
    "#1CE6FF",
    "#336600"
)

```


```{r, fig.width=14, fig.height=14}
from = match(edges$from, nodes_ct_hierarchy$name)
to = match(edges$to, nodes_ct_hierarchy$name)
conn_meta = data.frame(from=nodes_ct_hierarchy[from,]$name, to=nodes_ct_hierarchy[to,]$name) |>
  left_join(edges)

p = ggraph(G_ct, layout="dendrogram", circular=TRUE) + 
  geom_conn_bundle(
    data = get_con(from=from, to=to, coef=conn_meta$coef, pvalue=conn_meta$pvalue, group=conn_meta$group),
    aes(color=group, width=coef),
    tension=0.5) +
  geom_node_point(aes(color=cell_type, shape=type), size=8, stroke=2, fill="grey") + 
  scale_edge_color_brewer(type="qual") + 
  theme_void() + 
  geom_text_repel(aes(x=x, y=y, label=gene), size=5 ) + 
  geom_label_repel(aes(x=x, y=y, label=cell_type_label), size=8, force=3, alpha=.8) + 
  coord_fixed() +
  scale_shape_manual(values=c("receptor"=23, "ligand"=19))  +
  scale_color_manual(values=zeileis_28)
p

ggsave("cell2cell.pdf")
```


---

```{r}
sce <- Seurat::as.SingleCellExperiment(kidneyimmune)
```

```{r}
p <- plot_cpdb2(cell_type1 = 'B cell', cell_type2 = 'CD4T cell',
    scdata = sce,
    idents = 'celltype', # column name where the cell ids are located in the metadata
    means = means2,
    pvals = pvals2,
    deconvoluted = decon2, # new options from here on specific to plot_cpdb2
    desiredInteractions = list(
        c('CD4T cell', 'B cell'),
        c('B cell', 'CD4T cell')),
    interaction_grouping = interaction_annotation,
    edge_group_colors = c(
        "Activating" = "#e15759",
        "Chemotaxis" = "#59a14f",
        "Inhibitory" = "#4e79a7",
        "Intracellular trafficking" = "#9c755f",
        "DC_development" = "#B07aa1",
        "Unknown" = "#e7e7e7"
        ),
    node_group_colors = c(
        "CD4T cell" = "red",
        "B cell" = "blue"),
    keep_significant_only = TRUE,
    standard_scale = TRUE,
    remove_self = TRUE
    )
p
```

