---
title: "Untitled"
output: html_document
params:
  sce_path: "../../data/20_integrate_scrnaseq_data/scissor/adata_by_sample/adata.doublet_filtered_lambrechts_2018_luad_6149v2_3.rds"
  survival_path: "../../tables/tcga/mmc1.xlsx"
  kras_mutation: "../../tables/tcga/kras_mutated.tsv"
  braf_mutation: "../../tables/tcga/braf_mutated.tsv"
  egfr_mutation: "../../tables/tcga/egfr_mutated.tsv"
  tcga_tpm_path: "../../data/13_tcga/tcga-lung-primary.rds"  
  cpus: 1
  id: test
  artifact_dir: "/data/scratch/sturm/tmp"
  meta: NULL
  input_dir: NULL
---


```{r, include=FALSE}
library(conflicted)
library(Scissor)
library(readxl)
library(SingleCellExperiment)
library(readxl)
library(dplyr)
conflict_prefer("filter", "dplyr")
library(readr)
library(stringr)
# library(RhpcBLASctl)
```

```{r}
# # TODO test/train split, put into separate script
# lusc = read_tsv("../../data/13_tcga/TCGA-LUSC-PrimaryTumor-TPM.txt.gz")
# luad = read_tsv("../../data/13_tcga/TCGA-LUAD-PrimaryTumor-TPM.txt.gz")
# tcga_lung = luad %>% 
#   inner_join(lusc, by=c("ENSGID", "GeneName")) %>%
#   select(-ENSGID) %>%
#   group_by(GeneName) %>%
#   summarise_all(sum) %>% 
#   tibble::column_to_rownames("GeneName") %>%
#   as.matrix()
# 
# colnames_new = sapply(colnames(tcga_lung), function(x) {paste(str_split(x, pattern="-")[[1]][1:3], collapse="-")}, USE.NAMES = FALSE)
# colnames(tcga_lung) = colnames_new
# 
# # for now, exclude duplicates
# tcga_lung = tcga_lung[, !duplicated(colnames(tcga_lung))]
# 
# saveRDS(tcga_lung, "../../data/13_tcga/tcga-lung-primary.rds", compress=FALSE)
```

```{r}
# # Example data
# load("scRNA-seq.RData")
# load("./TCGA_LUAD_exp1.RData")
# load("./TCGA_LUAD_survival.RData")
```

### Load data
```{r}
sce = readRDS(params$sce_path)

# According to the example dataset, bulk data are TPM (not log-transformed).
clinical_data = read_excel(params$survival_path, guess_max=1000000, na=c("", "[Not Available]")) %>% 
  filter(type %in% c("LUAD", "LUSC")) %>% 
  select(TCGA_patient_barcode=bcr_patient_barcode, time=OS.time, status=OS, ajcc_pathologic_tumor_stage) %>%
  mutate(tumor_stage = if_else(
    ajcc_pathologic_tumor_stage %in% c("Stage I", "Stage IA", "Stage IB", "Stage II", "Stage IIA", "Stage IIB"),
    0,
    ifelse(ajcc_pathologic_tumor_stage %in% c("Stage III", "Stage IIIA", "Stage IIIB", "Stage IV"), 1, NA))) %>%
  mutate(
    kras_mutation = if_else(TCGA_patient_barcode %in% read_tsv(params$kras_mutation)$case_submitter_id, 1, 0),
    braf_mutation = if_else(TCGA_patient_barcode %in% read_tsv(params$braf_mutation)$case_submitter_id, 1, 0),
    egfr_mutation = if_else(TCGA_patient_barcode %in% read_tsv(params$egfr_mutation)$case_submitter_id, 1, 0),
    random = if_else(runif(nrow(.)) < 0.25, 1, 0)
  )

tcga_expr = readRDS(params$tcga_tpm_path)

common_patients = sort(intersect(colnames(tcga_expr), clinical_data$TCGA_patient_barcode))

clinical_data = clinical_data %>% 
  filter(TCGA_patient_barcode %in% common_patients) %>% 
  arrange(TCGA_patient_barcode)
tcga_expr = tcga_expr[, common_patients]
```
### Preprocess single cell data
```{r}
sc_dataset = Seurat_preprocessing(assays(sce)$X)
```

```{r, fig.width=6, fig.height=5}
DimPlot(sc_dataset, reduction = 'umap', label = T, label.size = 5)
```

### execute scissor for survival

```{r}
dim(tcga_expr)
stopifnot(all(colnames(tcga_expr) == clinical_data$TCGA_patient_barcode))
```

```{r}
phenotype <- clinical_data %>% select(time, status)
```

```{r}
scissor_rdata = file.path(params$artifact_dir, paste0(params$id, '_scissor_survival.RData'))

infos1 <- Scissor(tcga_expr, sc_dataset, phenotype, alpha = 0.05,
                 family = "cox", Save_file = scissor_rdata)
```

```{r}
Scissor_select <- rep(NA, ncol(sc_dataset))
names(Scissor_select) <- colnames(sc_dataset)
# it is a bit counterintuitive, but scissor+ -> worse survival, scissor- -> better survival
Scissor_select[infos1$Scissor_pos] <- "worse survival"
Scissor_select[infos1$Scissor_neg] <- "better survival"
sc_dataset_meta <- AddMetaData(sc_dataset, metadata = Scissor_select, col.name = "scissor")
plot1 =DimPlot(sc_dataset_meta, reduction = 'umap', group.by = 'scissor', cols = c('royalblue','indianred1'), pt.size = .2, order = c(2,1))
```
```{r}
write_tsv(as.data.frame(Scissor_select) %>% as_tibble(rownames="cell_id"), file.path(params$artifact_dir, paste0(params$id, "_scissor_survival.tsv")))
```

### execute scissor for binary variables 

```{r}
lapply(c("tumor_stage", "kras_mutation", "braf_mutation", "egfr_mutation"), function(variable) {
# lapply(c("random"), function(variable) {
  message(variable)
  clinical_data_subset = clinical_data %>% filter(!!as.name(variable) %in% c(0, 1))
  tcga_expr_subset = tcga_expr[, clinical_data_subset$TCGA_patient_barcode]
  stopifnot(all(colnames(tcga_expr_subset) == clinical_data_subset$TCGA_patient_barcode))
  message(dim(tcga_expr_subset))

  scissor_rdata = file.path(params$artifact_dir, paste0(params$id, '_scissor_', variable, '.RData'))
  infos2 <- Scissor(tcga_expr_subset, sc_dataset, clinical_data_subset[[variable]], tag=c(0, 1),
                 family = "binomial", Save_file = scissor_rdata)
  
  Scissor_select <- rep(NA, ncol(sc_dataset))
  names(Scissor_select) <- colnames(sc_dataset)
  # it is a bit counterintuitive, but scissor+ -> worse survival, scissor- -> better survival
  Scissor_select[infos2$Scissor_pos] <- "scissor+"
  Scissor_select[infos2$Scissor_neg] <- "scissor-"
  sc_dataset_meta <- AddMetaData(sc_dataset, metadata = Scissor_select, col.name = "scissor")
  print(DimPlot(sc_dataset_meta, reduction = 'umap', group.by = 'scissor', cols = c('royalblue','indianred1'), pt.size = .2, order = c(2,1)))
  write_tsv(as.data.frame(Scissor_select) %>% as_tibble(rownames="cell_id"), file.path(params$artifact_dir, paste0(params$id, "_scissor_", variable, ".tsv")))
})
```


### tests (too slow, excluded for now)
```{r}
# load("Scissor_LUAD_survival.RData")
```


```{r}
# computationally very expensive, leave for now! 
# numbers <- length(infos1$Scissor_pos) + length(infos1$Scissor_neg)
# result1 <- reliability.test(X, Y, network, alpha = 0.05, family = "cox", cell_num = numbers, n = 10, nfold = 10)
# saveRDS(result1, file="result1.rds")
```

```{r}
# evaulate_summary = evaluate.cell("Scissor_LUAD_survival.RData", infos1, FDR=.05, bootstrap_n=100)
# saveRDS(evaulate_summary, file="evaluate_summary.rds")
```






