---
title: "2nd gen deconvolution"
output: html_document
---


```{r}
library(conflicted)
library(omnideconv)
library(dplyr)
library(readr)
library(readxl)
library(cowplot)
library(ggplot2)
library(tidyr)
conflict_prefer("filter", "dplyr")
conflict_prefer("rename", "dplyr")
```

```{r}
tcga_clinical_data = read_tsv("../../tables/tcga/clinical_data_for_scissor.tsv")
tcga_tpm = read_rds("../../data/13_tcga/for_scissor/nsclc_primary_tumor.rds")
tcga_age = suppressWarnings(read_excel("../../tables/tcga/mmc1.xlsx") %>% select(TCGA_patient_barcode=bcr_patient_barcode, age=age_at_initial_pathologic_diagnosis))
tcga_treatment = read_tsv("../../tables/tcga/tcga_treatment.tsv")
```

```{r}
tcga_clinical_data = tcga_clinical_data %>% 
  left_join(tcga_age)
```

```{r}
sce = read_rds("/home/sturm/Downloads/sce/adata_primary_downsampled.rds")
```


```{r}
cibersortx_results = read_csv("../../tables/cibersortx/tcga_nsclc/CIBERSORTx_Job2_Results.csv")
cibersortx_results_tidy = cibersortx_results |> select(-c(`P-value`, `Correlation`, `RMSE`, `Absolute score (sig.score)`)) |> separate(Mixture, into=c(NA, "TCGA_patient_barcode", "origin"), sep="_") |> filter(origin == "T") |> select(-origin) |> pivot_longer(-TCGA_patient_barcode, names_to="cell_type", values_to="estimate") |> inner_join(tcga_clinical_data)
```

```{r, fig.width=12, fig.height=}
cibersortx_results_tidy |> filter(type == "LUAD") |> ggplot(aes(x=cell_type, y=estimate, color=as.factor(egfr_mutation))) + geom_boxplot() + theme_cowplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + background_grid()
```

other methods


```{r}
# dwls, bisque, cibersortx
model = omnideconv::build_model(sce, cell_type_column_name="cell_type_major", method="bisque")
results_bisque = omnideconv::deconvolute(tcga_tpm, model, method="bisque", single_cell_object=sce, cell_type_column_name="cell_type_major", batch_ids=colData(sce)$dataset)
```

```{r}
# dwls, bisque, cibersortx
# TODO exclude "other" cells
model = omnideconv::build_model(sce, cell_type_column_name="cell_type_major", method="dwls")
results_dwls = omnideconv::deconvolute(tcga_tpm, model, method="dwls", single_cell_object=sce, cell_type_column_name="cell_type_major", batch_ids=colData(sce)$dataset)
```

```{r}
results_tidy_bisque = results_bisque |>  as_tibble(rownames="TCGA_patient_barcode") |> pivot_longer(-TCGA_patient_barcode, names_to="cell_type", values_to="estimate") |> inner_join(tcga_clinical_data)
```

```{r, fig.width=12, fig.height=}
results_tidy |> filter(type == "LUAD") |> ggplot(aes(x=cell_type, y=estimate, color=as.factor(egfr_mutation))) + geom_boxplot() + theme_cowplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + background_grid()
```

