```{r, include=FALSE}
library(conflicted)
library(readxl)
library(SingleCellExperiment)
library(readxl)
library(dplyr)
conflict_prefer("filter", "dplyr")
library(readr)
library(stringr)
library(tidyr)
library(tibble)
# library(RhpcBLASctl)
```

```{r}
process_dataset = function(df) {
  df %>% 
    select(-ENSGID) %>%
    # aggregate duplicate gene symbols by sum
    group_by(GeneName) %>%
    summarise_all(sum) %>%
    column_to_rownames("GeneName") %>% t() %>% as_tibble(rownames="sample")
}

lusc = read_tsv("../../data/13_tcga/TCGA-LUSC-PrimaryTumor-TPM.txt.gz")%>%
  process_dataset() %>% mutate(origin = "T", condition = "LUSC", .after=1)
luad = read_tsv("../../data/13_tcga/TCGA-LUAD-PrimaryTumor-TPM.txt.gz")%>%
  process_dataset() %>% mutate(origin = "T", condition = "LUAD", .after=1)
lusc_norm = read_tsv("../../data/13_tcga/TCGA-LUSC-SolidTissueNormal-TPM.txt.gz") %>%
  process_dataset() %>% mutate(origin = "N", condition = "LUSC", .after=1)
luad_norm = read_tsv("../../data/13_tcga/TCGA-LUAD-SolidTissueNormal-TPM.txt.gz") %>%
  process_dataset() %>% mutate(origin = "N", condition = "LUAD", .after=1)

tcga_treatment = read_tsv("../../tables/tcga/tcga_treatment.tsv")

stopifnot(all(colnames(lusc) == colnames(luad)))
stopifnot(all(colnames(lusc) == colnames(lusc_norm)))
stopifnot(all(colnames(lusc) == colnames(luad_norm)))

tcga_lung = bind_rows(lusc, luad, lusc_norm, luad_norm) |> 
  mutate(patient = sapply(sample, function(x) {paste(str_split(x, pattern="-")[[1]][1:3], collapse="-")}), .after=1) |> 
  # aggregate multiple replicates by mean
  select(-sample) %>% 
  group_by(condition, patient, origin) %>%
  summarise_all(mean) %>%
  ungroup()|> 
  mutate(sample = sprintf("%s_%s_%s", condition, patient, origin), .before=1)
```

```{r}
metadata = tcga_lung |> select(sample, condition, origin, patient)
write_tsv(metadata, "../../data/13_tcga/for_cibersortx/metadata.tsv")

nsclc_primary_scissor = tcga_lung |> filter(origin == "T") |> select(-sample, -origin, -condition) |> column_to_rownames("patient") |> t()
write_rds(nsclc_primary_scissor, "../../data/13_tcga/for_scissor/nsclc_primary_tumor.rds")

# lusc_primary_scissor = tcga_lung |> filter(origin == "T", condition == "LUSC") |> select(-sample, -origin, -condition) |> column_to_rownames("patient") |> t()
# write_rds(lusc_primary_scissor, "../../data/13_tcga/for_scissor/lusc_primary_tumor.rds")
# 
# luad_primary_scissor = tcga_lung |> filter(origin == "T", condition == "LUAD") |> select(-sample, -origin, -condition) |> column_to_rownames("patient") |> t()
# write_rds(luad_primary_scissor, "../../data/13_tcga/for_scissor/luad_primary_scissor.rds")

nsclc_cibersortx = tcga_lung |> filter(condition == "LUAD") |> select(-patient, -origin, -condition) |> column_to_rownames("sample") |> t() |> as.data.frame()
# rounding will significantly reduce tsv file size and should not affect results at this precision. 
write_tsv(round(nsclc_cibersortx[, 1:15], digits=5) |> as_tibble(rownames="GeneSymbol"), "../../data/13_tcga/for_cibersortx/tcga_bulk_matrix_test_luad.txt")
write_tsv(round(nsclc_cibersortx, digits=5) |> as_tibble(rownames="GeneSymbol"), "../../data/13_tcga/for_cibersortx/tcga_bulk_matrix_luad.txt")

```

```{r}
# Response to chemotyerapy
selected_treatments = tcga_treatment |> 
  filter(tumor %in% c("LUAD", "LUSC"), !is.na(bcr_drug_barcode)) |>
  select(drug_name, measure_of_response, type=tumor, patient_barcode, therapy_type, treatment_n) |>
  filter(treatment_n == 1) |> # only 1st line 
  mutate(TCGA_patient_barcode = str_to_upper(patient_barcode)) |> 
  filter(therapy_type == "chemotherapy", !is.na(measure_of_response))


response_to_chemotherapy = selected_treatments |>
  group_by(TCGA_patient_barcode) |> 
  summarise(response_to_chemotherapy=ifelse(all(measure_of_response == "complete response"), 1, ifelse(all(measure_of_response == "clinical progressive disease"), 0, NA)))
```


```{r}
set.seed(0)
clinical_data = read_excel("../../tables/tcga/mmc1.xlsx", guess_max=1000000, na=c("", "[Not Available]")) %>%
  filter(type %in% c("LUAD", "LUSC")) %>%
  select(TCGA_patient_barcode=bcr_patient_barcode, time=OS.time, status=OS, ajcc_pathologic_tumor_stage, type) %>%
  left_join(response_to_chemotherapy, by="TCGA_patient_barcode") %>% 
  mutate(tumor_stage = if_else(
    ajcc_pathologic_tumor_stage %in% c("Stage I", "Stage IA", "Stage IB", "Stage II", "Stage IIA", "Stage IIB"),
    0,
    ifelse(ajcc_pathologic_tumor_stage %in% c("Stage III", "Stage IIIA", "Stage IIIB", "Stage IV"), 1, NA))) %>%
  mutate(
    kras_mutation = if_else(TCGA_patient_barcode %in% read_tsv("../../tables/tcga/kras_mutated.tsv")$case_submitter_id, 1, 0),
    braf_mutation = if_else(TCGA_patient_barcode %in% read_tsv("../../tables/tcga/braf_mutated.tsv")$case_submitter_id, 1, 0),
    egfr_mutation = if_else(TCGA_patient_barcode %in% read_tsv("../../tables/tcga/egfr_mutated.tsv")$case_submitter_id, 1, 0),
    tp53_mutation = if_else(TCGA_patient_barcode %in% read_tsv("../../tables/tcga/tp53_mutated.tsv")$case_submitter_id, 1, 0),
    stk11_mutation = if_else(TCGA_patient_barcode %in% read_tsv("../../tables/tcga/stk11_mutated.tsv")$case_submitter_id, 1, 0),
    tumor_type = if_else(type == "LUAD", 0, 1),
    random = if_else(runif(nrow(.)) < 0.25, 1, 0)
  )
```

```{r}
write_tsv(clinical_data, "../../tables/tcga/clinical_data_for_scissor.tsv")
```
